### ISSUE TITLE
[Discussion] Add CI.

### ISSUE THREAD

**Issue by theavege** [RutarAndriy/Lazarus_Learning#1]
<b>Hello.</b>

I like your project.
I want to add [CI](https://github.com/iso4free/lazarus-games/pull/2) for your project.
What do you think about this?

<i>Thanks.</i>

**Comment by RutarAndriy** [comment]
Thank you for your message. The code for this project is only partially mine - most of the code was taken from books and tutorials on Youtybe. Since this is a learning project, I would like to keep it as simple as possible. I don't think it needs an automatic build system.

Sorry.
